[pytest]
spark_options =
    spark.app.name: pytest-spark
    spark.ui.enabled: true
    spark.jars.packages: io.delta:delta-core_2.12:latest.integration
    spark.databricks.delta.snapshotPartitions: 2
    spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.sql.sources.parallelPartitionDiscovery.parallelism: 5
    delta.log.cacheSize: 3